#!/usr/bin/env bash
#
# Phase 0.5 host probe: find out what the webhosting really does before
# anything is built on it. Uploads a throwaway /_probe/ folder, reads the
# results back, and removes it again. See scripts/probe/README.md for what
# each result decides.
#
# Usage: scripts/probe/probe.sh <command> [options]
#
#   --upload        stage www/, upload it to /_probe/, start the background
#                   run, print the URLs and the konsoleH cron lines to set up
#   --read          fetch every result and print a summary (raw JSON is kept
#                   in scripts/probe/results/<time>/)
#   --background    (re)start the 10-minute background run on its own
#   --remove        delete the whole /_probe/ folder from the server
#
#   --with-ai       with --upload: also copy ANTHROPIC_KEY and OPENAI_KEY from
#                   the repo .env into the probe's private config, so that
#                   --read --ai can make ONE real Claude call and ONE OpenAI
#                   TTS call (cents). ElevenLabs is never called.
#   --ai            with --read: make those two calls
#   --dry-run       with --upload/--remove: print the sftp batch, touch nothing
#   --env-file F    repo settings (SFTP_*, SITE_BASE_URL) from F, not .env
#   -h, --help      this text
#
# The probe key lives in scripts/probe/probe.env (gitignored, created on the
# first --upload). It guards every probe endpoint; nothing else of the real
# site is involved.

set -euo pipefail

PROBE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$PROBE_DIR/../.." && pwd)"

# shellcheck source=scripts/lib/log.sh
. "$REPO_ROOT/scripts/lib/log.sh"
# shellcheck source=scripts/lib/env.sh
. "$REPO_ROOT/scripts/lib/env.sh"
# shellcheck source=scripts/lib/sftp.sh
. "$REPO_ROOT/scripts/lib/sftp.sh"

ENV_FILE="$REPO_ROOT/.env"
PROBE_ENV="$PROBE_DIR/probe.env"
UPLOADED="$PROBE_DIR/.uploaded"
WWW="$PROBE_DIR/www"
REMOTE_BASE="/_probe"
# Files the probe's PHP creates at runtime (for --remove).
RUNTIME_FILES=(
  private/var/probe.sqlite private/var/probe.sqlite-wal private/var/probe.sqlite-shm
  private/var/probe.sqlite-journal private/var/probe.lock private/var/background.log
  private/var/background.lock private/var/cron.log private/var/tts.mp3
)

CMD="" WITH_AI=0 AI=0 DRY_RUN=0
while [ $# -gt 0 ]; do
  case "$1" in
    --upload|--read|--background|--remove)
      [ -z "$CMD" ] || die "one command at a time ($CMD and $1)"; CMD="${1#--}" ;;
    --with-ai)  WITH_AI=1 ;;
    --ai)       AI=1 ;;
    --dry-run)  DRY_RUN=1 ;;
    --env-file) shift; ENV_FILE="${1:-}"; [ -n "$ENV_FILE" ] || die "--env-file needs a path" ;;
    -h|--help)  sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *)          die "unknown option: $1 (try --help)" ;;
  esac
  shift
done
[ -n "$CMD" ] || { sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'; exit 1; }

require_tools curl
require_env "$ENV_FILE" SITE_BASE_URL
SITE_URL=$(env_value "$ENV_FILE" SITE_BASE_URL); SITE_URL="${SITE_URL%/}"
PROBE_URL="$SITE_URL$REMOTE_BASE"
# The URL path of the site (non-empty when SITE_BASE_URL has a path).
SITE_PATH=$(printf '%s' "$SITE_URL" | sed -E 's|^[a-zA-Z]+://[^/]+||')

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

probe_key() {
  if ! env_has "$PROBE_ENV" PROBE_KEY; then
    [ "$CMD" = upload ] || die "no probe key yet ($PROBE_ENV) — run --upload first"
    # A dry run must not leave anything behind, not even a local key file.
    if [ "$DRY_RUN" -eq 1 ]; then printf 'dry-run-placeholder-key'; return 0; fi
    ( umask 077; printf '# Probe key for /_probe/ (scripts/probe). Gitignored.\nPROBE_KEY=%s\n' "$(openssl rand -hex 24)" > "$PROBE_ENV" )
    ok "generated a probe key in scripts/probe/probe.env" >&2
  fi
  env_value "$PROBE_ENV" PROBE_KEY
}

# Single-quoted PHP string literal.
php_str() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\'/\\\'}"
  printf "'%s'" "$s"
}

# --- upload ------------------------------------------------------------------------

stage() {
  local key="$1" stage_dir="$WORK/stage"
  mkdir -p "$stage_dir"
  rsync -a --exclude '.DS_Store' "$WWW/" "$stage_dir/"
  # The rewrite base is the URL path of htaccess-test/, which depends on where
  # the site lives (SITE_BASE_URL may carry a path).
  sed -i.bak "s|^\( *RewriteBase \).*|\1$SITE_PATH$REMOTE_BASE/htaccess-test/|" "$stage_dir/htaccess-test/.htaccess"
  rm -f "$stage_dir/htaccess-test/.htaccess.bak"
  {
    printf '<?php\n// Generated by scripts/probe/probe.sh — probe key%s. Denied over HTTP.\n' \
      "$([ "$WITH_AI" -eq 1 ] && printf ' and AI keys')"
    printf 'return [\n    %s => %s,\n' "$(php_str key)" "$(php_str "$key")"
    if [ "$WITH_AI" -eq 1 ]; then
      local a o
      a=$(env_value "$ENV_FILE" ANTHROPIC_KEY); o=$(env_value "$ENV_FILE" OPENAI_KEY)
      [ -n "$a" ] || warn "ANTHROPIC_KEY not set — the Claude call will be skipped" >&2
      [ -n "$o" ] || warn "OPENAI_KEY not set — the TTS call will be skipped" >&2
      printf '    %s => %s,\n    %s => %s,\n' "$(php_str anthropic_key)" "$(php_str "$a")" "$(php_str openai_key)" "$(php_str "$o")"
    fi
    printf '];\n'
  } > "$stage_dir/private/config.php"
  chmod 600 "$stage_dir/private/config.php"
  printf 'deny-check\n' > "$stage_dir/private/deny-check.txt"
  printf '%s\n' "$stage_dir"
}

upload() {
  local key stage_dir batch d f
  key=$(probe_key)
  stage_dir=$(stage "$key")

  # 1. directories and the two deny rules, 2. HTTP proof that private/ is
  # denied, 3. only then the config with the key, 4. everything else.
  batch="$WORK/1.batch"; : > "$batch"
  printf -- '-mkdir %s\n' "$(sq "$(rpath "$REMOTE_BASE")")" >> "$batch"
  while IFS= read -r d; do
    printf -- '-mkdir %s\n' "$(sq "$(rpath "$REMOTE_BASE/${d#./}")")" >> "$batch"
  done < <(cd "$stage_dir" && find . -mindepth 1 -type d | LC_ALL=C sort)
  printf -- '-mkdir %s\n' "$(sq "$(rpath "$REMOTE_BASE/private/var")")" >> "$batch"
  for f in .htaccess private/.htaccess private/deny-check.txt; do
    printf 'put %s %s\n' "$(sq "$stage_dir/$f")" "$(sq "$(rpath "$REMOTE_BASE/$f")")" >> "$batch"
  done

  local batch2="$WORK/2.batch"; : > "$batch2"
  printf 'put %s %s\n' "$(sq "$stage_dir/private/config.php")" "$(sq "$(rpath "$REMOTE_BASE/private/config.php")")" >> "$batch2"
  printf -- '-chmod 600 %s\n' "$(sq "$(rpath "$REMOTE_BASE/private/config.php")")" >> "$batch2"
  while IFS= read -r f; do
    f="${f#./}"
    case "$f" in .htaccess|private/.htaccess|private/deny-check.txt|private/config.php) continue ;; esac
    printf 'put %s %s\n' "$(sq "$stage_dir/$f")" "$(sq "$(rpath "$REMOTE_BASE/$f")")" >> "$batch2"
  done < <(cd "$stage_dir" && find . -type f | LC_ALL=C sort)

  if [ "$DRY_RUN" -eq 1 ]; then
    info "Dry run — target $SFTP_USER@$SFTP_HOST:$SFTP_PORT, remote '$(rpath "$REMOTE_BASE")'"
    info "batch 1 (directories, deny rules, marker):"
    sed "s|$stage_dir/|<stage>/|g" "$batch" | sed 's/^/    /'
    info "then: GET $PROBE_URL/private/deny-check.txt must answer 403"
    info "batch 2 (config with the probe key$([ "$WITH_AI" -eq 1 ] && printf ' + AI keys'), everything else):"
    sed "s|$stage_dir/|<stage>/|g" "$batch2" | sed 's/^/    /'
    info "Dry run complete; nothing was uploaded"
    return 0
  fi

  info "Uploading the probe to $PROBE_URL/"
  sftp_batch "$batch" || die "could not create /_probe/ or its deny rules"
  local got
  got=$(curl -sS -o /dev/null -w '%{http_code}' --max-time 20 "$PROBE_URL/private/deny-check.txt" 2>/dev/null || echo 000)
  [ "$got" = 403 ] || die "$PROBE_URL/private/deny-check.txt answered $got, not 403 — private/ is not protected; the key was NOT uploaded. Run --remove."
  ok "private/ answers 403"
  sftp_batch "$batch2" || die "probe upload failed"
  ( cd "$stage_dir" && find . -type f | sed 's|^\./||' | LC_ALL=C sort ) > "$UPLOADED"
  ok "$(wc -l < "$UPLOADED" | tr -d ' ') file(s) uploaded"

  start_background "$key"
  print_setup "$key"
}

start_background() {
  local key="$1" got
  got=$(curl -sS -o /dev/null -w '%{http_code}' --max-time 20 -H "Authorization: Bearer $key" "$PROBE_URL/background.php" 2>/dev/null || echo 000)
  case "$got" in
    200) ok "background run started — read it back after 10+ minutes (--read)" ;;
    409) warn "a background run is already in progress" ;;
    *)   bad "background.php answered $got" ;;
  esac
}

print_setup() {
  local key="$1" masked
  masked="${key:0:4}…${key: -4}"
  mkdir -p "$PROBE_DIR/results"
  (
    umask 077
    {
      printf "a) * * * * * /usr/bin/curl --silent --show-error --connect-timeout 2 --max-time 5 --request POST --header 'Authorization: Bearer %s' '%s/cron-probe.php'\n" "$key" "$PROBE_URL"
      printf 'b) %s/cron-probe.php?key=%s\n' "$PROBE_URL" "$key"
      printf 'c) <web root>/_probe/cron-cli.php  (PHP script job)\n'
    } > "$PROBE_DIR/results/cron-lines.txt"
  )
  printf '\n'
  info "Set up ONE of these as a konsoleH cron job, every minute, and leave it 24 h:"
  printf '\n  a) command (preferred — tells whether headers work):\n'
  printf "     * * * * * /usr/bin/curl --silent --show-error --connect-timeout 2 --max-time 5 --request POST --header 'Authorization: Bearer %s' '%s/cron-probe.php'\n" "$masked" "$PROBE_URL"
  printf '\n  b) URL job (if the panel only takes a URL):\n'
  printf '     %s/cron-probe.php?key=%s\n' "$PROBE_URL" "$masked"
  printf '\n  c) PHP script job (if the panel runs PHP scripts — a CLI tick would\n'
  printf '     avoid the FPM time limit): <web root>/_probe/cron-cli.php\n'
  printf '     (the absolute web-root path is paths.script_dir in --read)\n\n'
  ok "the key is masked above; complete lines: scripts/probe/results/cron-lines.txt"
  ok "if you can, set up a) AND c): the log shows which ones arrive"
}

# --- read ----------------------------------------------------------------------------

# One HTTP check → a TSV line for summarize.php:
#   group  label  url-path  status  content-type  header-of-interest  verdict  note
CHECKS=""
check() { # GROUP LABEL PATH WANT_STATUS [--type T] [--header NAME SUBSTR] [--header-not NAME SUBSTR] [--absent NAME] [--body-not S] [--gzip] [-- curl args]
  local group="$1" label="$2" path="$3" want="$4"; shift 4
  local want_type="" hname="" hwant="" nname="" nwant="" absent="" body_not="" gzip=0 extra=()
  while [ $# -gt 0 ]; do
    case "$1" in
      --type)       want_type="$2"; shift 2 ;;
      --header)     hname="$2"; hwant="$3"; shift 3 ;;
      --header-not) nname="$2"; nwant="$3"; shift 3 ;;
      --absent)     absent="$2"; shift 2 ;;
      --body-not)   body_not="$2"; shift 2 ;;
      --gzip)       gzip=1; shift ;;
      --)           shift; extra=("$@"); break ;;
      *)            die "check: bad option $1" ;;
    esac
  done
  local hdr="$WORK/h.$RANDOM" body="$WORK/b.$RANDOM" status type verdict=pass note="" hval=""
  : > "$hdr"; : > "$body"
  local args=(-sS --max-time 20 -o "$body" -D "$hdr")
  [ "$gzip" -eq 1 ] && args+=(-H 'Accept-Encoding: gzip')
  curl "${args[@]}" ${extra[@]+"${extra[@]}"} "$PROBE_URL$path" >/dev/null 2>&1 || true
  status=$(awk 'toupper($1) ~ /^HTTP\// { s = $2 } END { print s + 0 }' "$hdr" 2>/dev/null || echo 0)
  type=$(tr -d '\r' < "$hdr" 2>/dev/null | awk 'tolower($1) == "content-type:" { $1 = ""; sub(/^ /, ""); t = $0 } END { print t }')
  header() { tr -d '\r' < "$hdr" | awk -v n="$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]')" 'index(tolower($0), n ":") == 1 { sub(/^[^:]*:[ \t]*/, ""); v = $0 } END { print v }'; }
  case " $want " in *" $status "*) ;; *) verdict=fail; note="status $status, want $want" ;; esac
  if [ -n "$want_type" ] && [ "$verdict" = pass ]; then
    case "$type" in "$want_type"*) ;; *) verdict=fail; note="type '$type', want $want_type" ;; esac
  fi
  if [ -n "$hname" ]; then
    hval=$(header "$hname")
    if [ "$verdict" = pass ]; then
      case "$hval" in *"$hwant"*) ;; *) verdict=fail; note="$hname '${hval:-none}', want *$hwant*" ;; esac
    fi
  fi
  if [ -n "$nname" ] && [ "$verdict" = pass ]; then
    case "$(header "$nname")" in *"$nwant"*) verdict=fail; note="$nname contains '$nwant'" ;; esac
  fi
  if [ -n "$absent" ] && [ "$verdict" = pass ] && [ -n "$(header "$absent")" ]; then
    verdict=fail; note="$absent present"
  fi
  if [ "$gzip" -eq 1 ] && [ "$verdict" = pass ]; then
    hval=$(header content-encoding)
    [ "$hval" = gzip ] || { verdict=fail; note="content-encoding '${hval:-none}'"; }
  fi
  if [ -n "$body_not" ] && [ -f "$body" ] && grep -q "$body_not" "$body"; then
    verdict=fail; note="body contains '$body_not'"
  fi
  # A JSON body is kept for the summary (echo/ini endpoints).
  local json=""
  case "$type" in application/json*) json=$(tr -d '\n\t' < "$body" | cut -c1-400) ;; esac
  CHECKS+="$group"$'\t'"$label"$'\t'"$path"$'\t'"$status"$'\t'"$type"$'\t'"${hval}"$'\t'"$verdict"$'\t'"$note"$'\t'"$json"$'\n'
  rm -f "$hdr" "$body"
}

read_results() {
  local key out stamp auth
  key=$(probe_key)
  stamp=$(date -u +%Y%m%dT%H%M%SZ)
  out="$PROBE_DIR/results/$stamp"
  mkdir -p "$out"
  auth=(-H "Authorization: Bearer $key")
  info "Reading $PROBE_URL/ → scripts/probe/results/$stamp/"

  local q="cli=1"; [ "$AI" -eq 1 ] && q="$q&ai=1"
  # The HTTP status goes next to each body: a 500 is a finding, not "no data".
  fetch() { # NAME URL MAX_TIME
    curl -sS --max-time "$3" "${auth[@]}" -o "$out/$1.json" -w '%{http_code}' "$2" > "$out/$1.status" 2>/dev/null \
      || warn "$1: request failed ($(cat "$out/$1.status" 2>/dev/null || echo no status))"
  }
  fetch probe "$PROBE_URL/probe.php?$q" 90
  fetch background "$PROBE_URL/background.php?read=1" 20
  fetch cron "$PROBE_URL/cron-probe.php?read=1" 20

  local B='Authorization: Bearer probe-test-not-the-key'
  check htaccess "directives accepted (DirectoryIndex)" /htaccess-test/ 200 --type text/html
  check htaccess "SPA fallback serves the shell"       /htaccess-test/some/deep/route 200 --type text/html
  check htaccess "missing asset stays a 404"           /htaccess-test/missing.js 404
  check htaccess "JS gzipped (text/javascript)"        /htaccess-test/app.js 200 --gzip
  check htaccess "JS content type"                     /htaccess-test/app.js 200 --type text/javascript
  check htaccess "manifest type"                       /htaccess-test/manifest.webmanifest 200 --type application/manifest+json
  check htaccess "webp type"                           /htaccess-test/image.webp 200 --type image/webp
  check htaccess "mp3 type"                            /htaccess-test/sound.mp3 200 --type audio/mpeg
  check htaccess "sw.js revalidates"                   /htaccess-test/sw.js 200 --header cache-control no-cache
  check htaccess "JSON immutable on 200"               /htaccess-test/data.json 200 --header cache-control immutable
  check htaccess "404 not marked immutable"            /htaccess-test/nope.json 404 --header-not cache-control immutable
  check htaccess "nosniff header"                      /htaccess-test/ 200 --header x-content-type-options nosniff
  check htaccess "Referrer-Policy (not no-referrer)"   /htaccess-test/ 200 --header referrer-policy strict-origin-when-cross-origin
  check htaccess "X-Powered-By removed"                /htaccess-test/echo.php 200 --absent x-powered-by
  check htaccess "dotfiles denied"                     /htaccess-test/.htaccess 403
  check htaccess "Require all denied"                  /htaccess-test/private/secret.txt 403
  check htaccess "no directory listing"                /htaccess-test/expr/ 403
  check expr    "conditional header: 200 immutable"    /htaccess-test/expr/data.json 200 --header cache-control immutable
  check expr    "conditional header: 404 no-store"     /htaccess-test/expr/missing.json 404 --header cache-control no-store
  check media   "script in upload dir not executed"    /htaccess-test/media/evil.php 403 --body-not EXECUTED
  check media   "media served"                         /htaccess-test/media/sound.mp3 200 --type audio/mpeg
  check auth    "Bearer reaches PHP with SetEnvIf"     /htaccess-test/echo.php 200 --type application/json -- -H "$B"
  check auth    "Bearer reaches PHP without SetEnvIf"  /echo-auth.php 200 --type application/json -- -H "$B"
  check auth    "Bearer reaches PHP via CGIPassAuth"   /cgipassauth/echo.php 200 --type application/json -- -H "$B"
  check ini     ".user.ini upload limits"              /htaccess-test/userini/ini.php 200 --type application/json
  check ini     "php_value in .htaccess"               /htaccess-test/phpvalue/ini.php "200 500"
  check ini     "php_flag in .htaccess"                /htaccess-test/phpflag/ini.php "200 500"
  check private "probe config denied"                  /private/config.php 403
  check private "probe logs denied"                    /private/var/cron.log 403
  check private "probe index not listed"               /private/ 403
  printf '%s' "$CHECKS" > "$out/checks.tsv"

  if command -v php >/dev/null 2>&1; then
    php "$PROBE_DIR/summarize.php" "$out"
  else
    warn "no local php — raw results are in $out"
  fi
}

# --- remove ------------------------------------------------------------------------

# Every entry of the remote tree under /_probe (files and directories, dotfiles
# included), deepest first, discovered with `ls -la` one level per session.
remote_tree() {
  local level=("$REMOTE_BASE") next batch out dir
  : > "$WORK/tree.files"; : > "$WORK/tree.dirs"
  while [ ${#level[@]} -gt 0 ]; do
    batch="$WORK/ls.batch"; out="$WORK/ls.out"; : > "$batch"
    for dir in "${level[@]}"; do printf -- '-ls -la %s\n' "$(sq "$(rpath "$dir")")" >> "$batch"; done
    run_sftp "$batch" > "$out" 2>/dev/null || true
    next=()
    while IFS=$'\t' read -r kind path; do
      case "$kind" in
        d) printf '%s\n' "$path" >> "$WORK/tree.dirs"; next+=("$path") ;;
        f) printf '%s\n' "$path" >> "$WORK/tree.files" ;;
      esac
    done < <(awk -v prefix="$SFTP_REMOTE_PREFIX" '
      /^sftp> / { dir = $0; sub(/^sftp> -?ls -la /, "", dir); gsub(/^"|"$/, "", dir)
                  if (prefix != "" && index(dir, prefix) == 1) dir = substr(dir, length(prefix) + 1); next }
      NF >= 9 && ($1 ~ /^[d-]/) {
        name = $0; for (i = 1; i <= 8; i++) sub(/^[^ ]+ +/, "", name); sub(/.*\//, "", name)
        if (name == "." || name == "..") next
        printf "%s\t%s/%s\n", ($1 ~ /^d/ ? "d" : "f"), dir, name
      }' "$out")
    level=(${next[@]+"${next[@]}"})
  done
}

remove() {
  local batch="$WORK/rm.batch" f d
  : > "$batch"
  # Known files first (works even when listing is impossible), then whatever
  # a listing finds, then the directories deepest first.
  {
    [ -f "$UPLOADED" ] && sed "s|^|$REMOTE_BASE/|" "$UPLOADED"
    ( cd "$WWW" && find . -type f | sed "s|^\./|$REMOTE_BASE/|" )
    printf '%s\n' "$REMOTE_BASE/private/config.php" "$REMOTE_BASE/private/deny-check.txt"
    for f in "${RUNTIME_FILES[@]}"; do printf '%s/%s\n' "$REMOTE_BASE" "$f"; done
  } | LC_ALL=C sort -u > "$WORK/known.files"
  if [ "$DRY_RUN" -eq 0 ]; then remote_tree; else : > "$WORK/tree.files"; : > "$WORK/tree.dirs"; fi
  LC_ALL=C sort -u "$WORK/known.files" "$WORK/tree.files" > "$WORK/all.files"
  while IFS= read -r f; do printf -- '-rm %s\n' "$(sq "$(rpath "$f")")" >> "$batch"; done < "$WORK/all.files"
  {
    cat "$WORK/tree.dirs"
    ( cd "$WWW" && find . -mindepth 1 -type d | sed "s|^\./|$REMOTE_BASE/|" )
    printf '%s\n' "$REMOTE_BASE/private/var"
  } | LC_ALL=C sort -u | awk '{ print gsub(/\//, "/") "\t" $0 }' | sort -rn | cut -f2 > "$WORK/all.dirs"
  while IFS= read -r d; do printf -- '-rmdir %s\n' "$(sq "$(rpath "$d")")" >> "$batch"; done < "$WORK/all.dirs"
  printf -- '-rmdir %s\n' "$(sq "$(rpath "$REMOTE_BASE")")" >> "$batch"

  if [ "$DRY_RUN" -eq 1 ]; then
    info "Dry run — would run on $SFTP_USER@$SFTP_HOST:$SFTP_PORT:"
    sed 's/^/    /' "$batch"
    return 0
  fi
  info "Removing $PROBE_URL/"
  sftp_batch "$batch" >/dev/null 2>&1 || true
  local st=0
  remote_exists "$REMOTE_BASE" || st=$?
  case "$st" in
    1) ok "/_probe/ is gone"; rm -f "$UPLOADED" ;;
    0) bad "/_probe/ still exists — rerun, or delete it over SFTP"; exit 1 ;;
    *) warn "could not confirm the removal (connection trouble) — rerun --remove" ;;
  esac
}

# --- main --------------------------------------------------------------------------

case "$CMD" in
  upload)
    require_tools sshpass sftp rsync openssl
    load_sftp_credentials "$ENV_FILE"
    [ "$AI" -eq 0 ] || die "--ai belongs to --read (use --with-ai on --upload)"
    upload ;;
  read)
    [ "$DRY_RUN" -eq 0 ] || die "--dry-run applies to --upload and --remove"
    read_results ;;
  background)
    start_background "$(probe_key)" ;;
  remove)
    require_tools sshpass sftp
    load_sftp_credentials "$ENV_FILE"
    remove ;;
esac
